// src/Header.svelte
<section>
    <nav id="navbar">
        <header class="sticky-top pt-5">
            <div class="row d-flex justify-content-between ">
                <div class="col-lg-4 col-md-6 col-sm-4 row">
                    <a class="navbar-brand col-1" href="/">
                        <img
                            src="/images/logo.png"
                            alt="Logo Elias Schneider"
                            class="logo"
                        />
                    </a>
                    <h1 class="col-1">
                        <div class="hide">E</div>
                        lias&nbsp;Schneider
                    </h1>
                </div>

                <div
                    class="col-lg-2 col-md-4 col-sm-2 d-flex justify-content-between"
                >
                    <a class=" mobile-none" href="#skills">Skills</a>
                    <a class=" mobile-none" href="#projects">Projects</a>
                </div>
            </div>
        </header>
    </nav>
</section>

<style>
    h1 {
        font-size: 25px;
    }
    @media screen and (max-width: 700px) {
        h1 {
            font-size: 15px;
        }
    }
</style>

// app/components/Header.tsx
import Image from "next/image";

export default function Header() {
  return (
    <div className="container my-5">
      <div className="flex items-center">
        <Image
          height={40}
          width={40}
          src="/images/logo.png"
          alt="Elias Schneider Logo"
        />
        <h1 className="ml-2 text-2xl font-bold">
          <span className="hidden">E</span>lias Schneider
        </h1>
      </div>
    </div>
  );
}
